# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RequestClousureTest3' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RequestClousureTest3
    pod 'Alamofire'
    pod 'SDWebImage'
  target 'RequestClousureTest3Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RequestClousureTest3UITests' do
    # Pods for testing
  end

end
